<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;

class ScheduleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Room 7-1
        DB::table('schedules')->insert([
            ['id' => 1, 'subject_level_id' => NULL, 'lesson_id' => 1, 'teacher_id' => NULL, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 2, 'subject_level_id' => 1, 'lesson_id' => 2, 'teacher_id' => 47, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 3, 'subject_level_id' => 1, 'lesson_id' => 3, 'teacher_id' => 47, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 4, 'subject_level_id' => NULL, 'lesson_id' => 4, 'teacher_id' => NULL, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 5, 'subject_level_id' => 2, 'lesson_id' => 5, 'teacher_id' => 16, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 6, 'subject_level_id' => 3, 'lesson_id' => 6, 'teacher_id' => 51, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 7, 'subject_level_id' => NULL, 'lesson_id' => 7, 'teacher_id' => NULL, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 8, 'subject_level_id' => 4, 'lesson_id' => 8, 'teacher_id' => 40, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 9, 'subject_level_id' => NULL, 'lesson_id' => 9, 'teacher_id' => NULL, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 10, 'subject_level_id' => 5, 'lesson_id' => 10, 'teacher_id' => 37, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 11, 'subject_level_id' => 5, 'lesson_id' => 11, 'teacher_id' => 37, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 12, 'subject_level_id' => 2, 'lesson_id' => 12, 'teacher_id' => 16, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 13, 'subject_level_id' => NULL, 'lesson_id' => 13, 'teacher_id' => NULL, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 14, 'subject_level_id' => 7, 'lesson_id' => 14, 'teacher_id' => 20, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 15, 'subject_level_id' => 8, 'lesson_id' => 15, 'teacher_id' => 19, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 16, 'subject_level_id' => NULL, 'lesson_id' => 16, 'teacher_id' => NULL, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 17, 'subject_level_id' => 8, 'lesson_id' => 17, 'teacher_id' => 19, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 18, 'subject_level_id' => NULL, 'lesson_id' => 18, 'teacher_id' => NULL, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 19, 'subject_level_id' => 4, 'lesson_id' => 19, 'teacher_id' => 39, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 20, 'subject_level_id' => 4, 'lesson_id' => 20, 'teacher_id' => 39, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 21, 'subject_level_id' => 9, 'lesson_id' => 21, 'teacher_id' => 22, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 22, 'subject_level_id' => 9, 'lesson_id' => 23, 'teacher_id' => 22, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 23, 'subject_level_id' => NULL, 'lesson_id' => 22, 'teacher_id' => NULL, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 24, 'subject_level_id' => 9, 'lesson_id' => 21, 'teacher_id' => 20, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 25, 'subject_level_id' => 9, 'lesson_id' => 23, 'teacher_id' => 20, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 26, 'subject_level_id' => 10, 'lesson_id' => 24, 'teacher_id' => 38, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 27, 'subject_level_id' => NULL, 'lesson_id' => 25, 'teacher_id' => NULL, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 28, 'subject_level_id' => 10, 'lesson_id' => 26, 'teacher_id' => 38, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 29, 'subject_level_id' => NULL, 'lesson_id' => 27, 'teacher_id' => NULL, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 30, 'subject_level_id' => 1, 'lesson_id' => 28, 'teacher_id' => 47, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 31, 'subject_level_id' => 1, 'lesson_id' => 29, 'teacher_id' => 47, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 32, 'subject_level_id' => 2, 'lesson_id' => 30, 'teacher_id' => 16, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 33, 'subject_level_id' => NULL, 'lesson_id' => 31, 'teacher_id' => NULL, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 34, 'subject_level_id' => 8, 'lesson_id' => 32, 'teacher_id' => 19, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 35, 'subject_level_id' => 7, 'lesson_id' => 33, 'teacher_id' => 20, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 36, 'subject_level_id' => NULL, 'lesson_id' => 34, 'teacher_id' => NULL, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 37, 'subject_level_id' => NULL, 'lesson_id' => 35, 'teacher_id' => NULL, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 38, 'subject_level_id' => NULL, 'lesson_id' => 36, 'teacher_id' => NULL, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 39, 'subject_level_id' => NULL, 'lesson_id' => 37, 'teacher_id' => NULL, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 40, 'subject_level_id' => 6, 'lesson_id' => 38, 'teacher_id' => 7, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 41, 'subject_level_id' => 6, 'lesson_id' => 39, 'teacher_id' => 7, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 42, 'subject_level_id' => NULL, 'lesson_id' => 40, 'teacher_id' => NULL, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 43, 'subject_level_id' => 11, 'lesson_id' => 41, 'teacher_id' => 16, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 44, 'subject_level_id' => 1, 'lesson_id' => 42, 'teacher_id' => 47, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 45, 'subject_level_id' => 2, 'lesson_id' => 44, 'teacher_id' => 16, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 46, 'subject_level_id' => 3, 'lesson_id' => 45, 'teacher_id' => 51, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 47, 'subject_level_id' => NULL, 'lesson_id' => 46, 'teacher_id' => NULL, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 48, 'subject_level_id' => 3, 'lesson_id' => 47, 'teacher_id' => 51, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 49, 'subject_level_id' => 11, 'lesson_id' => 48, 'teacher_id' => 16, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 50, 'subject_level_id' => 4, 'lesson_id' => 50, 'teacher_id' => 39, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 51, 'subject_level_id' => NULL, 'lesson_id' => 51, 'teacher_id' => NULL, 'room_id' => 1, 'semester_id' => 1],
        ]);

        // Room 7-2
        DB::table('schedules')->insert([
            ['id' => 52, 'subject_level_id' => null, 'lesson_id' => 1, 'teacher_id' => null, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 53, 'subject_level_id' => 6, 'lesson_id' => 2, 'teacher_id' => 7, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 54, 'subject_level_id' => 6, 'lesson_id' => 3, 'teacher_id' => 7, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 55, 'subject_level_id' => null, 'lesson_id' => 4, 'teacher_id' => null, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 56, 'subject_level_id' => 10, 'lesson_id' => 5, 'teacher_id' => 38, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 57, 'subject_level_id' => 10, 'lesson_id' => 6, 'teacher_id' => 38, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 58, 'subject_level_id' => null, 'lesson_id' => 7, 'teacher_id' => null, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 59, 'subject_level_id' => 3, 'lesson_id' => 8, 'teacher_id' => 51, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 60, 'subject_level_id' => null, 'lesson_id' => 9, 'teacher_id' => null, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 61, 'subject_level_id' => 7, 'lesson_id' => 10, 'teacher_id' => 20, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 62, 'subject_level_id' => 7, 'lesson_id' => 11, 'teacher_id' => 20, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 63, 'subject_level_id' => 1, 'lesson_id' => 12, 'teacher_id' => 47, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 64, 'subject_level_id' => null, 'lesson_id' => 13, 'teacher_id' => null, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 65, 'subject_level_id' => 2, 'lesson_id' => 14, 'teacher_id' => 16, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 66, 'subject_level_id' => 2, 'lesson_id' => 15, 'teacher_id' => 16, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 67, 'subject_level_id' => null, 'lesson_id' => 16, 'teacher_id' => null, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 68, 'subject_level_id' => 2, 'lesson_id' => 17, 'teacher_id' => 16, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 69, 'subject_level_id' => null, 'lesson_id' => 18, 'teacher_id' => null, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 70, 'subject_level_id' => 5, 'lesson_id' => 19, 'teacher_id' => 36, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 71, 'subject_level_id' => 5, 'lesson_id' => 20, 'teacher_id' => 36, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 72, 'subject_level_id' => 9, 'lesson_id' => 21, 'teacher_id' => 20, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 73, 'subject_level_id' => null, 'lesson_id' => 22, 'teacher_id' => null, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 74, 'subject_level_id' => 9, 'lesson_id' => 23, 'teacher_id' => 20, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 75, 'subject_level_id' => 9, 'lesson_id' => 21, 'teacher_id' => 22, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 76, 'subject_level_id' => 9, 'lesson_id' => 23, 'teacher_id' => 22, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 77, 'subject_level_id' => 4, 'lesson_id' => 24, 'teacher_id' => 23, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 78, 'subject_level_id' => null, 'lesson_id' => 25, 'teacher_id' => null, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 79, 'subject_level_id' => 4, 'lesson_id' => 26, 'teacher_id' => 39, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 80, 'subject_level_id' => null, 'lesson_id' => 27, 'teacher_id' => null, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 81, 'subject_level_id' => 8, 'lesson_id' => 28, 'teacher_id' => 19, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 82, 'subject_level_id' => 8, 'lesson_id' => 29, 'teacher_id' => 19, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 83, 'subject_level_id' => 1, 'lesson_id' => 30, 'teacher_id' => 47, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 84, 'subject_level_id' => null, 'lesson_id' => 31, 'teacher_id' => null, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 85, 'subject_level_id' => 1, 'lesson_id' => 32, 'teacher_id' => 47, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 86, 'subject_level_id' => 2, 'lesson_id' => 33, 'teacher_id' => 16, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 87, 'subject_level_id' => null, 'lesson_id' => 34, 'teacher_id' => null, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 88, 'subject_level_id' => null, 'lesson_id' => 35, 'teacher_id' => null, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 89, 'subject_level_id' => null, 'lesson_id' => 36, 'teacher_id' => null, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 90, 'subject_level_id' => null, 'lesson_id' => 37, 'teacher_id' => null, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 91, 'subject_level_id' => 4, 'lesson_id' => 38, 'teacher_id' => 39, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 92, 'subject_level_id' => 4, 'lesson_id' => 39, 'teacher_id' => 39, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 93, 'subject_level_id' => null, 'lesson_id' => 40, 'teacher_id' => null, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 94, 'subject_level_id' => 1, 'lesson_id' => 41, 'teacher_id' => 47, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 95, 'subject_level_id' => 8, 'lesson_id' => 42, 'teacher_id' => 19, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 96, 'subject_level_id' => 1, 'lesson_id' => 44, 'teacher_id' => 47, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 97, 'subject_level_id' => 11, 'lesson_id' => 45, 'teacher_id' => 16, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 98, 'subject_level_id' => null, 'lesson_id' => 46, 'teacher_id' => null, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 99, 'subject_level_id' => 11, 'lesson_id' => 47, 'teacher_id' => 16, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 100, 'subject_level_id' => 3, 'lesson_id' => 48, 'teacher_id' => 51, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 101, 'subject_level_id' => 3, 'lesson_id' => 50, 'teacher_id' => 51, 'room_id' => 2, 'semester_id' => 1],
            ['id' => 102, 'subject_level_id' => null, 'lesson_id' => 51, 'teacher_id' => null, 'room_id' => 2, 'semester_id' => 1],
        ]);

        // Room 8-1
        DB::table('schedules')->insert([
            ['id' => 103, 'subject_level_id' => null, 'lesson_id' => 1, 'teacher_id' => null, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 104, 'subject_level_id' => 2, 'lesson_id' => 2, 'teacher_id' => 55, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 105, 'subject_level_id' => 2, 'lesson_id' => 3, 'teacher_id' => 55, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 106, 'subject_level_id' => null, 'lesson_id' => 4, 'teacher_id' => null, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 107, 'subject_level_id' => 3, 'lesson_id' => 5, 'teacher_id' => 45, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 108, 'subject_level_id' => 3, 'lesson_id' => 6, 'teacher_id' => 45, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 109, 'subject_level_id' => null, 'lesson_id' => 7, 'teacher_id' => null, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 110, 'subject_level_id' => 1, 'lesson_id' => 8, 'teacher_id' => 47, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 111, 'subject_level_id' => 1, 'lesson_id' => 9, 'teacher_id' => 47, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 112, 'subject_level_id' => 1, 'lesson_id' => 10, 'teacher_id' => 47, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 113, 'subject_level_id' => 1, 'lesson_id' => 11, 'teacher_id' => 47, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 114, 'subject_level_id' => 5, 'lesson_id' => 12, 'teacher_id' => 36, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 115, 'subject_level_id' => null, 'lesson_id' => 13, 'teacher_id' => null, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 116, 'subject_level_id' => 5, 'lesson_id' => 14, 'teacher_id' => 36, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 117, 'subject_level_id' => 7, 'lesson_id' => 15, 'teacher_id' => 20, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 118, 'subject_level_id' => null, 'lesson_id' => 16, 'teacher_id' => null, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 119, 'subject_level_id' => 3, 'lesson_id' => 17, 'teacher_id' => 45, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 120, 'subject_level_id' => 8, 'lesson_id' => 18, 'teacher_id' => 19, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 121, 'subject_level_id' => 9, 'lesson_id' => 19, 'teacher_id' => 20, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 122, 'subject_level_id' => 9, 'lesson_id' => 20, 'teacher_id' => 20, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 123, 'subject_level_id' => 9, 'lesson_id' => 19, 'teacher_id' => 22, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 124, 'subject_level_id' => 9, 'lesson_id' => 20, 'teacher_id' => 22, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 125, 'subject_level_id' => 5, 'lesson_id' => 21, 'teacher_id' => 36, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 126, 'subject_level_id' => null, 'lesson_id' => 22, 'teacher_id' => null, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 127, 'subject_level_id' => 6, 'lesson_id' => 23, 'teacher_id' => 7, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 128, 'subject_level_id' => 6, 'lesson_id' => 24, 'teacher_id' => 7, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 129, 'subject_level_id' => null, 'lesson_id' => 25, 'teacher_id' => null, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 130, 'subject_level_id' => 6, 'lesson_id' => 26, 'teacher_id' => 7, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 131, 'subject_level_id' => 7, 'lesson_id' => 27, 'teacher_id' => 20, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 132, 'subject_level_id' => 4, 'lesson_id' => 28, 'teacher_id' => 39, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 133, 'subject_level_id' => 4, 'lesson_id' => 29, 'teacher_id' => 39, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 134, 'subject_level_id' => 8, 'lesson_id' => 30, 'teacher_id' => 19, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 135, 'subject_level_id' => null, 'lesson_id' => 31, 'teacher_id' => null, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 136, 'subject_level_id' => 10, 'lesson_id' => 32, 'teacher_id' => 38, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 137, 'subject_level_id' => null, 'lesson_id' => 34, 'teacher_id' => null, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 138, 'subject_level_id' => 10, 'lesson_id' => 33, 'teacher_id' => 38, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 139, 'subject_level_id' => 10, 'lesson_id' => 35, 'teacher_id' => 38, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 140, 'subject_level_id' => 10, 'lesson_id' => 36, 'teacher_id' => 38, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 141, 'subject_level_id' => null, 'lesson_id' => 37, 'teacher_id' => null, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 142, 'subject_level_id' => 8, 'lesson_id' => 38, 'teacher_id' => 19, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 143, 'subject_level_id' => 8, 'lesson_id' => 39, 'teacher_id' => 19, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 144, 'subject_level_id' => null, 'lesson_id' => 40, 'teacher_id' => null, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 145, 'subject_level_id' => 2, 'lesson_id' => 41, 'teacher_id' => 55, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 146, 'subject_level_id' => 3, 'lesson_id' => 42, 'teacher_id' => 45, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 147, 'subject_level_id' => 4, 'lesson_id' => 43, 'teacher_id' => 39, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 148, 'subject_level_id' => 4, 'lesson_id' => 44, 'teacher_id' => 39, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 149, 'subject_level_id' => 4, 'lesson_id' => 45, 'teacher_id' => 39, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 150, 'subject_level_id' => null, 'lesson_id' => 46, 'teacher_id' => null, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 151, 'subject_level_id' => 2, 'lesson_id' => 47, 'teacher_id' => 55, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 152, 'subject_level_id' => 1, 'lesson_id' => 48, 'teacher_id' => 47, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 153, 'subject_level_id' => 11, 'lesson_id' => 50, 'teacher_id' => 16, 'room_id' => 3, 'semester_id' => 1],
            ['id' => 154, 'subject_level_id' => 11, 'lesson_id' => 51, 'teacher_id' => 16, 'room_id' => 3, 'semester_id' => 1],
        ]);

        // Room 8-2
        DB::table('schedules')->insert([
            ['id' => 155, 'subject_level_id' => null, 'lesson_id' => 1, 'teacher_id' => null, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 156, 'subject_level_id' => 10, 'lesson_id' => 2, 'teacher_id' => 38, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 157, 'subject_level_id' => 10, 'lesson_id' => 3, 'teacher_id' => 38, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 158, 'subject_level_id' => null, 'lesson_id' => 4, 'teacher_id' => null, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 159, 'subject_level_id' => 6, 'lesson_id' => 5, 'teacher_id' => 7, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 160, 'subject_level_id' => 4, 'lesson_id' => 6, 'teacher_id' => 39, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 161, 'subject_level_id' => null, 'lesson_id' => 7, 'teacher_id' => null, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 162, 'subject_level_id' => 3, 'lesson_id' => 8, 'teacher_id' => 45, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 163, 'subject_level_id' => 3, 'lesson_id' => 9, 'teacher_id' => 45, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 164, 'subject_level_id' => 11, 'lesson_id' => 10, 'teacher_id' => 16, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 165, 'subject_level_id' => 11, 'lesson_id' => 11, 'teacher_id' => 16, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 166, 'subject_level_id' => 3, 'lesson_id' => 12, 'teacher_id' => 45, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 167, 'subject_level_id' => null, 'lesson_id' => 13, 'teacher_id' => null, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 168, 'subject_level_id' => 1, 'lesson_id' => 14, 'teacher_id' => 47, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 169, 'subject_level_id' => 5, 'lesson_id' => 15, 'teacher_id' => 36, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 170, 'subject_level_id' => null, 'lesson_id' => 16, 'teacher_id' => null, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 171, 'subject_level_id' => 1, 'lesson_id' => 17, 'teacher_id' => 47, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 172, 'subject_level_id' => 1, 'lesson_id' => 18, 'teacher_id' => 47, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 173, 'subject_level_id' => 9, 'lesson_id' => 19, 'teacher_id' => 22, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 174, 'subject_level_id' => 9, 'lesson_id' => 20, 'teacher_id' => 22, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 175, 'subject_level_id' => 9, 'lesson_id' => 19, 'teacher_id' => 20, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 176, 'subject_level_id' => 9, 'lesson_id' => 20, 'teacher_id' => 20, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 177, 'subject_level_id' => 6, 'lesson_id' => 21, 'teacher_id' => 7, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 178, 'subject_level_id' => null, 'lesson_id' => 22, 'teacher_id' => null, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 179, 'subject_level_id' => 10, 'lesson_id' => 23, 'teacher_id' => 38, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 180, 'subject_level_id' => 10, 'lesson_id' => 24, 'teacher_id' => 38, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 181, 'subject_level_id' => null, 'lesson_id' => 25, 'teacher_id' => null, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 182, 'subject_level_id' => 5, 'lesson_id' => 26, 'teacher_id' => 36, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 183, 'subject_level_id' => 5, 'lesson_id' => 27, 'teacher_id' => 36, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 184, 'subject_level_id' => 7, 'lesson_id' => 28, 'teacher_id' => 20, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 185, 'subject_level_id' => 7, 'lesson_id' => 29, 'teacher_id' => 20, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 186, 'subject_level_id' => 4, 'lesson_id' => 30, 'teacher_id' => 39, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 187, 'subject_level_id' => null, 'lesson_id' => 31, 'teacher_id' => null, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 188, 'subject_level_id' => 4, 'lesson_id' => 32, 'teacher_id' => 39, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 189, 'subject_level_id' => 4, 'lesson_id' => 33, 'teacher_id' => 39, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 190, 'subject_level_id' => null, 'lesson_id' => 34, 'teacher_id' => null, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 191, 'subject_level_id' => 1, 'lesson_id' => 35, 'teacher_id' => 47, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 192, 'subject_level_id' => 1, 'lesson_id' => 36, 'teacher_id' => 47, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 193, 'subject_level_id' => null, 'lesson_id' => 37, 'teacher_id' => null, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 194, 'subject_level_id' => 2, 'lesson_id' => 38, 'teacher_id' => 55, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 195, 'subject_level_id' => 2, 'lesson_id' => 39, 'teacher_id' => 55, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 196, 'subject_level_id' => null, 'lesson_id' => 40, 'teacher_id' => null, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 197, 'subject_level_id' => 3, 'lesson_id' => 41, 'teacher_id' => 45, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 198, 'subject_level_id' => 4, 'lesson_id' => 42, 'teacher_id' => 39, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 199, 'subject_level_id' => 8, 'lesson_id' => 43, 'teacher_id' => 19, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 200, 'subject_level_id' => 8, 'lesson_id' => 44, 'teacher_id' => 19, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 201, 'subject_level_id' => 8, 'lesson_id' => 45, 'teacher_id' => 19, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 202, 'subject_level_id' => null, 'lesson_id' => 46, 'teacher_id' => null, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 203, 'subject_level_id' => 8, 'lesson_id' => 47, 'teacher_id' => 19, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 204, 'subject_level_id' => 2, 'lesson_id' => 48, 'teacher_id' => 55, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 205, 'subject_level_id' => 6, 'lesson_id' => 50, 'teacher_id' => 7, 'room_id' => 4, 'semester_id' => 1],
            ['id' => 206, 'subject_level_id' => 2, 'lesson_id' => 51, 'teacher_id' => 55, 'room_id' => 4, 'semester_id' => 1],
        ]);

        // Room 9-1
        DB::table('schedules')->insert([
            ['id' => 207, 'subject_level_id' => null, 'lesson_id' => 1, 'teacher_id' => null, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 208, 'subject_level_id' => 3, 'lesson_id' => 2, 'teacher_id' => 45, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 209, 'subject_level_id' => 3, 'lesson_id' => 3, 'teacher_id' => 45, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 210, 'subject_level_id' => null, 'lesson_id' => 4, 'teacher_id' => null, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 211, 'subject_level_id' => 4, 'lesson_id' => 5, 'teacher_id' => 39, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 212, 'subject_level_id' => 1, 'lesson_id' => 6, 'teacher_id' => 47, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 213, 'subject_level_id' => null, 'lesson_id' => 7, 'teacher_id' => null, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 214, 'subject_level_id' => 2, 'lesson_id' => 8, 'teacher_id' => 55, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 215, 'subject_level_id' => 2, 'lesson_id' => 9, 'teacher_id' => 55, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 216, 'subject_level_id' => 3, 'lesson_id' => 10, 'teacher_id' => 45, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 217, 'subject_level_id' => 3, 'lesson_id' => 11, 'teacher_id' => 45, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 218, 'subject_level_id' => 8, 'lesson_id' => 12, 'teacher_id' => 19, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 219, 'subject_level_id' => null, 'lesson_id' => 13, 'teacher_id' => null, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 220, 'subject_level_id' => 8, 'lesson_id' => 14, 'teacher_id' => 19, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 221, 'subject_level_id' => 1, 'lesson_id' => 15, 'teacher_id' => 47, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 222, 'subject_level_id' => null, 'lesson_id' => 16, 'teacher_id' => null, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 223, 'subject_level_id' => 5, 'lesson_id' => 17, 'teacher_id' => 36, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 224, 'subject_level_id' => 5, 'lesson_id' => 18, 'teacher_id' => 36, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 225, 'subject_level_id' => 10, 'lesson_id' => 19, 'teacher_id' => 38, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 226, 'subject_level_id' => 10, 'lesson_id' => 20, 'teacher_id' => 38, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 227, 'subject_level_id' => 10, 'lesson_id' => 21, 'teacher_id' => 38, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 228, 'subject_level_id' => null, 'lesson_id' => 22, 'teacher_id' => null, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 229, 'subject_level_id' => 5, 'lesson_id' => 23, 'teacher_id' => 36, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 230, 'subject_level_id' => 9, 'lesson_id' => 24, 'teacher_id' => 20, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 231, 'subject_level_id' => null, 'lesson_id' => 25, 'teacher_id' => null, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 232, 'subject_level_id' => 9, 'lesson_id' => 26, 'teacher_id' => 20, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 233, 'subject_level_id' => 9, 'lesson_id' => 24, 'teacher_id' => 22, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 234, 'subject_level_id' => 9, 'lesson_id' => 26, 'teacher_id' => 22, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 235, 'subject_level_id' => 6, 'lesson_id' => 27, 'teacher_id' => 7, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 236, 'subject_level_id' => 11, 'lesson_id' => 28, 'teacher_id' => 16, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 237, 'subject_level_id' => 11, 'lesson_id' => 29, 'teacher_id' => 16, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 238, 'subject_level_id' => 7, 'lesson_id' => 30, 'teacher_id' => 20, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 239, 'subject_level_id' => null, 'lesson_id' => 31, 'teacher_id' => null, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 240, 'subject_level_id' => 7, 'lesson_id' => 32, 'teacher_id' => 20, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 241, 'subject_level_id' => 8, 'lesson_id' => 33, 'teacher_id' => 19, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 242, 'subject_level_id' => null, 'lesson_id' => 34, 'teacher_id' => null, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 243, 'subject_level_id' => 4, 'lesson_id' => 35, 'teacher_id' => 39, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 244, 'subject_level_id' => 10, 'lesson_id' => 36, 'teacher_id' => 38, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 245, 'subject_level_id' => null, 'lesson_id' => 37, 'teacher_id' => null, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 246, 'subject_level_id' => 1, 'lesson_id' => 38, 'teacher_id' => 47, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 247, 'subject_level_id' => 1, 'lesson_id' => 39, 'teacher_id' => 47, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 248, 'subject_level_id' => null, 'lesson_id' => 40, 'teacher_id' => null, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 249, 'subject_level_id' => 8, 'lesson_id' => 41, 'teacher_id' => 19, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 250, 'subject_level_id' => 6, 'lesson_id' => 42, 'teacher_id' => 7, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 251, 'subject_level_id' => 2, 'lesson_id' => 43, 'teacher_id' => 55, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 252, 'subject_level_id' => 6, 'lesson_id' => 44, 'teacher_id' => 7, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 253, 'subject_level_id' => 1, 'lesson_id' => 45, 'teacher_id' => 47, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 254, 'subject_level_id' => null, 'lesson_id' => 46, 'teacher_id' => null, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 255, 'subject_level_id' => 4, 'lesson_id' => 47, 'teacher_id' => 39, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 256, 'subject_level_id' => 4, 'lesson_id' => 48, 'teacher_id' => 39, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 257, 'subject_level_id' => 2, 'lesson_id' => 50, 'teacher_id' => 55, 'room_id' => 5, 'semester_id' => 1],
            ['id' => 258, 'subject_level_id' => 4, 'lesson_id' => 51, 'teacher_id' => 39, 'room_id' => 5, 'semester_id' => 1],
        ]);

        // Room 9-2
        DB::table('schedules')->insert([
            ['id' => 259, 'subject_level_id' => null, 'lesson_id' => 1, 'teacher_id' => null, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 260, 'subject_level_id' => 4, 'lesson_id' => 2, 'teacher_id' => 39, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 261, 'subject_level_id' => 4, 'lesson_id' => 3, 'teacher_id' => 39, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 262, 'subject_level_id' => null, 'lesson_id' => 4, 'teacher_id' => null, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 263, 'subject_level_id' => 1, 'lesson_id' => 5, 'teacher_id' => 47, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 264, 'subject_level_id' => 2, 'lesson_id' => 6, 'teacher_id' => 55, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 265, 'subject_level_id' => null, 'lesson_id' => 7, 'teacher_id' => null, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 266, 'subject_level_id' => 5, 'lesson_id' => 8, 'teacher_id' => 36, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 267, 'subject_level_id' => 5, 'lesson_id' => 9, 'teacher_id' => 36, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 268, 'subject_level_id' => 8, 'lesson_id' => 10, 'teacher_id' => 19, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 269, 'subject_level_id' => 8, 'lesson_id' => 11, 'teacher_id' => 19, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 270, 'subject_level_id' => 11, 'lesson_id' => 12, 'teacher_id' => 16, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 271, 'subject_level_id' => null, 'lesson_id' => 13, 'teacher_id' => null, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 272, 'subject_level_id' => 3, 'lesson_id' => 14, 'teacher_id' => 45, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 273, 'subject_level_id' => 3, 'lesson_id' => 15, 'teacher_id' => 45, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 274, 'subject_level_id' => null, 'lesson_id' => 16, 'teacher_id' => null, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 275, 'subject_level_id' => 7, 'lesson_id' => 17, 'teacher_id' => 36, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 276, 'subject_level_id' => 11, 'lesson_id' => 18, 'teacher_id' => 16, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 277, 'subject_level_id' => 6, 'lesson_id' => 19, 'teacher_id' => 7, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 278, 'subject_level_id' => 6, 'lesson_id' => 20, 'teacher_id' => 7, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 279, 'subject_level_id' => 4, 'lesson_id' => 21, 'teacher_id' => 39, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 280, 'subject_level_id' => null, 'lesson_id' => 22, 'teacher_id' => null, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 281, 'subject_level_id' => 4, 'lesson_id' => 23, 'teacher_id' => 39, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 282, 'subject_level_id' => 9, 'lesson_id' => 24, 'teacher_id' => 20, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 283, 'subject_level_id' => null, 'lesson_id' => 25, 'teacher_id' => null, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 284, 'subject_level_id' => 9, 'lesson_id' => 26, 'teacher_id' => 20, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 285, 'subject_level_id' => 9, 'lesson_id' => 24, 'teacher_id' => 22, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 286, 'subject_level_id' => 9, 'lesson_id' => 26, 'teacher_id' => 22, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 287, 'subject_level_id' => 5, 'lesson_id' => 27, 'teacher_id' => 36, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 288, 'subject_level_id' => 10, 'lesson_id' => 28, 'teacher_id' => 38, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 289, 'subject_level_id' => 10, 'lesson_id' => 29, 'teacher_id' => 38, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 290, 'subject_level_id' => 10, 'lesson_id' => 30, 'teacher_id' => 38, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 291, 'subject_level_id' => null, 'lesson_id' => 31, 'teacher_id' => null, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 292, 'subject_level_id' => 10, 'lesson_id' => 32, 'teacher_id' => 38, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 293, 'subject_level_id' => 7, 'lesson_id' => 33, 'teacher_id' => 36, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 294, 'subject_level_id' => null, 'lesson_id' => 34, 'teacher_id' => null, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 295, 'subject_level_id' => 4, 'lesson_id' => 35, 'teacher_id' => 39, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 296, 'subject_level_id' => 8, 'lesson_id' => 36, 'teacher_id' => 19, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 297, 'subject_level_id' => null, 'lesson_id' => 37, 'teacher_id' => null, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 298, 'subject_level_id' => 3, 'lesson_id' => 38, 'teacher_id' => 45, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 299, 'subject_level_id' => 3, 'lesson_id' => 39, 'teacher_id' => 45, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 300, 'subject_level_id' => null, 'lesson_id' => 40, 'teacher_id' => null, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 301, 'subject_level_id' => 6, 'lesson_id' => 41, 'teacher_id' => 7, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 302, 'subject_level_id' => 2, 'lesson_id' => 42, 'teacher_id' => 55, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 303, 'subject_level_id' => 1, 'lesson_id' => 43, 'teacher_id' => 47, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 304, 'subject_level_id' => 2, 'lesson_id' => 44, 'teacher_id' => 55, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 305, 'subject_level_id' => 2, 'lesson_id' => 45, 'teacher_id' => 55, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 306, 'subject_level_id' => null, 'lesson_id' => 46, 'teacher_id' => null, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 307, 'subject_level_id' => 1, 'lesson_id' => 47, 'teacher_id' => 47, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 308, 'subject_level_id' => 8, 'lesson_id' => 48, 'teacher_id' => 19, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 309, 'subject_level_id' => 1, 'lesson_id' => 50, 'teacher_id' => 47, 'room_id' => 6, 'semester_id' => 1],
            ['id' => 310, 'subject_level_id' => 1, 'lesson_id' => 51, 'teacher_id' => 47, 'room_id' => 6, 'semester_id' => 1],
        ]);

        // Kurang data hari jumat di 7-1 dan 7-2
        DB::table('schedules')->insert([
            ['id' => 311, 'subject_level_id' => null, 'lesson_id' => 43, 'teacher_id' => null, 'room_id' => 1, 'semester_id' => 1],
            ['id' => 312, 'subject_level_id' => null, 'lesson_id' => 43, 'teacher_id' => null, 'room_id' => 2, 'semester_id' => 1],
        ]);

        
        
    }
}
